name: adaptive_progress_dialog
description: A Flutter package providing an adaptive progress dialog. Using this package you can perform async operation and get the result of the operation.
version: 1.0.3
repository: https://github.com/krzychudz/adaptive-progress-dialog
issue_tracker: https://github.com/krzychudz/adaptive-progress-dialog/issues

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
